// <auto-generated />
using System;
using AspergillosisEPR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspergillosisEPR.Migrations.Aspergillosis
{
    [DbContext(typeof(AspergillosisContext))]
    [Migration("20180925123025_AddPatientHeamotologies")]
    partial class AddPatientHeamotologies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormCategoryId");

                    b.Property<bool>("IsLocked");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormCategoryId");

                    b.ToTable("CaseReportForms");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("CaseReportFormCategories");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormField", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormFieldTypeId");

                    b.Property<int?>("CaseReportFormId");

                    b.Property<int?>("CaseReportFormSectionId");

                    b.Property<string>("Label")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormFieldTypeId");

                    b.HasIndex("CaseReportFormId");

                    b.HasIndex("CaseReportFormSectionId");

                    b.ToTable("CaseReportFormFields");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFieldOption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormFieldId");

                    b.Property<int>("CaseReportFormOptionChoiceId");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormFieldId");

                    b.HasIndex("CaseReportFormOptionChoiceId");

                    b.ToTable("CaseReportFormFieldOptions");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFieldType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("CaseReportFormFieldTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFormSection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormId");

                    b.Property<int>("CaseReportFormSectionId");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormId");

                    b.HasIndex("CaseReportFormSectionId");

                    b.ToTable("CaseReportFormFormSections");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormOptionChoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormOptionGroupId");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormOptionGroupId");

                    b.ToTable("CaseReportFormOptionChoices");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormOptionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("CaseReportFormOptionGroups");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormPatientResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormFieldId");

                    b.Property<int>("CaseReportFormId");

                    b.Property<int>("CaseReportFormResultId");

                    b.Property<DateTime?>("DateAnswer");

                    b.Property<decimal?>("NumericAnswer");

                    b.Property<int>("PatientId");

                    b.Property<string>("TextAnswer");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormFieldId");

                    b.HasIndex("CaseReportFormId");

                    b.HasIndex("CaseReportFormResultId");

                    b.HasIndex("PatientId");

                    b.ToTable("CaseReportFormPatientResults");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormPatientResultOptionChoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormOptionChoiceId");

                    b.Property<int>("CaseReportFormPatientResultId");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormPatientResultId");

                    b.ToTable("CaseReportFormPatientResultOptionChoices");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseReportFormCategoryId");

                    b.Property<int>("CaseReportFormId");

                    b.Property<DateTime>("DateTaken");

                    b.Property<int>("PatientId");

                    b.HasKey("ID");

                    b.HasIndex("CaseReportFormCategoryId");

                    b.HasIndex("CaseReportFormId");

                    b.HasIndex("PatientId");

                    b.ToTable("CaseReportFormResults");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormSection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("CaseReportFormSections");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.DbImport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DbImportTypeId");

                    b.Property<DateTime>("ImportedDate");

                    b.Property<string>("ImportedFileName");

                    b.Property<int>("PatientsCount");

                    b.HasKey("ID");

                    b.ToTable("DbImports");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.DbImportType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImporterClass")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("DbImportTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.DiagnosisCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("DiagnosisCategories");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.DiagnosisType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ShortName");

                    b.HasKey("ID");

                    b.ToTable("DiagnosisTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Drug", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Fungi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Fungis");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.ImmunoglobulinType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ImmunoglobulinTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<int?>("MedicalTrialPrincipalInvestigatorId");

                    b.Property<int>("MedicalTrialStatusId");

                    b.Property<int>("MedicalTrialTypeId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<string>("RECNumber");

                    b.Property<string>("RandDNumber");

                    b.HasKey("ID");

                    b.HasIndex("MedicalTrialPrincipalInvestigatorId");

                    b.HasIndex("MedicalTrialStatusId");

                    b.HasIndex("MedicalTrialTypeId");

                    b.ToTable("MedicalTrials");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrialPatientStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MedicalTrialPatientStatuses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrialPrincipalInvestigator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("PersonTitleId");

                    b.HasKey("ID");

                    b.HasIndex("PersonTitleId");

                    b.ToTable("MedicalTrialPrincipalInvestigators");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrialStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MedicalTrialStatuses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrialType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MedicalTrialTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.OtherAllergicItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("OtherAllergicItems");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DOB");

                    b.Property<DateTime?>("DateOfDeath");

                    b.Property<double>("DistanceFromWythenshawe");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("GenericNote");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("NhsNumber");

                    b.Property<int?>("PatientStatusId");

                    b.Property<string>("PostCode");

                    b.Property<string>("RM2Number")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("PatientStatusId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientAllergicIntoleranceItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AllergyIntoleranceItemId");

                    b.Property<string>("AllergyIntoleranceItemType");

                    b.Property<string>("IntoleranceType")
                        .IsRequired();

                    b.Property<string>("Note")
                        .HasColumnType("ntext");

                    b.Property<int>("PatientId");

                    b.Property<string>("Severity");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAllergicIntoleranceItems");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientAllergicIntoleranceItemSideEffect", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PatientAllergicIntoleranceItemId");

                    b.Property<int>("SideEffectId");

                    b.HasKey("ID");

                    b.HasIndex("PatientAllergicIntoleranceItemId");

                    b.HasIndex("SideEffectId");

                    b.ToTable("PatientAllergicIntoleranceItemSideEffects");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDiagnosis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<int>("DiagnosisCategoryId");

                    b.Property<DateTime?>("DiagnosisDate");

                    b.Property<int>("DiagnosisTypeId");

                    b.Property<int>("PatientId");

                    b.HasKey("ID");

                    b.HasIndex("DiagnosisCategoryId");

                    b.HasIndex("DiagnosisTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDiagnosis");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrug", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DrugId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("PatientId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("DrugId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDrugs");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrugLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComparisionCharacter");

                    b.Property<DateTime>("DateReceived");

                    b.Property<DateTime>("DateTaken");

                    b.Property<int>("DrugId");

                    b.Property<string>("LabNumber");

                    b.Property<int>("PatientId");

                    b.Property<decimal>("ResultValue");

                    b.Property<int>("UnitOfMeasurementId");

                    b.HasKey("ID");

                    b.HasIndex("DrugId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("PatientDrugLevel");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrugSideEffect", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PatientDrugId");

                    b.Property<int>("SideEffectId");

                    b.HasKey("ID");

                    b.HasIndex("PatientDrugId");

                    b.HasIndex("SideEffectId");

                    b.ToTable("PatientDrugSideEffects");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientExamination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("PatientImmunoglobulinId");

                    b.Property<int>("PatientMeasurementId");

                    b.Property<int>("PatientRadiologyFinidingId");

                    b.Property<int>("PatientSTGQuestionnaireId");

                    b.Property<int>("PatientVisitId");

                    b.HasKey("ID");

                    b.HasIndex("PatientImmunoglobulinId");

                    b.HasIndex("PatientMeasurementId");

                    b.HasIndex("PatientRadiologyFinidingId");

                    b.HasIndex("PatientSTGQuestionnaireId");

                    b.HasIndex("PatientVisitId");

                    b.ToTable("PatientExaminations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PatientExamination");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientHaematology", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Albumin");

                    b.Property<DateTime>("DateTaken");

                    b.Property<double>("Hb");

                    b.Property<int>("PatientId");

                    b.Property<double>("WBC");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientHaematologies");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientImmunoglobulin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTaken");

                    b.Property<int>("ImmunoglobulinTypeId");

                    b.Property<int>("PatientId");

                    b.Property<decimal>("Value");

                    b.HasKey("ID");

                    b.HasIndex("ImmunoglobulinTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientImmunoglobulins");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTaken");

                    b.Property<decimal?>("Height");

                    b.Property<int>("PatientId");

                    b.Property<decimal?>("Weight");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMeasurements");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientMedicalTrial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Consented");

                    b.Property<DateTime?>("ConsentedDate");

                    b.Property<DateTime>("IdentifiedDate");

                    b.Property<int>("MedicalTrialId");

                    b.Property<int>("PatientId");

                    b.Property<int>("PatientMedicalTrialStatusId");

                    b.Property<DateTime?>("RecruitedDate");

                    b.HasKey("ID");

                    b.HasIndex("MedicalTrialId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientMedicalTrialStatusId");

                    b.ToTable("PatientMedicalTrials");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientPulmonaryFunctionTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateTaken");

                    b.Property<int>("PatientId");

                    b.Property<decimal>("PredictedValue");

                    b.Property<int>("PulmonaryFunctionTestId");

                    b.Property<decimal>("ResultValue");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.HasIndex("PulmonaryFunctionTestId");

                    b.ToTable("PatientPulmonaryFunctionTests");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientRadiologyFinding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChestDistributionId");

                    b.Property<int?>("ChestLocationId");

                    b.Property<DateTime?>("DateTaken");

                    b.Property<int>("FindingId");

                    b.Property<int?>("GradeId");

                    b.Property<string>("Note")
                        .HasColumnType("ntext");

                    b.Property<int>("PatientId");

                    b.Property<int>("RadiologyTypeId");

                    b.Property<int?>("TreatmentResponseId");

                    b.HasKey("ID");

                    b.HasIndex("ChestDistributionId");

                    b.HasIndex("ChestLocationId");

                    b.HasIndex("FindingId");

                    b.HasIndex("GradeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RadiologyTypeId");

                    b.HasIndex("TreatmentResponseId");

                    b.ToTable("PatientRadiologyFindings");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSmokingDrinkingStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("AlcolholUnits");

                    b.Property<double?>("CigarettesPerDay");

                    b.Property<double?>("PacksPerYear");

                    b.Property<int>("PatientId");

                    b.Property<int>("SmokingStatusId");

                    b.Property<int?>("StartAge");

                    b.Property<int?>("StopAge");

                    b.HasKey("ID");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("SmokingStatusId");

                    b.ToTable("PatientSmokingDrinkingStatuses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PatientStatuses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSTGQuestionnaire", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ActivityScore")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateTaken");

                    b.Property<decimal>("ImpactScore")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("OriginalImportedId");

                    b.Property<int>("PatientId");

                    b.Property<decimal>("SymptomScore")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientSTGQuestionnaires");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSurgery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<int>("PatientId");

                    b.Property<int?>("SurgeryDate");

                    b.Property<int>("SurgeryId");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.HasIndex("SurgeryId");

                    b.ToTable("PatientSurgeries");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientVisit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PatientId");

                    b.Property<DateTime>("VisitDate");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientVisits");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.PersonTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PersonTitles");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.PulmonaryFunctionTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("ID");

                    b.ToTable("PulmonaryFunctionTests");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.ChestDistribution", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ChestDistributions");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.ChestLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ChestLocations");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.Finding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.Grade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.RadiologyType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("RadiologyTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Radiology.TreatmentResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TreatmentResponses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Reporting.PatientReportItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PatientId");

                    b.Property<int>("ReportId");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReportId");

                    b.ToTable("PatientReportItems");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Reporting.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("ReportTypeId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Reporting.ReportType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Discriminator");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ReportTypes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.SideEffect", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SideEffects");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.SmokingStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("SmokingStatuses");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Surgery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Surgeries");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.TemporaryNewPatient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ImportedAsRealPatient");

                    b.Property<string>("RM2Number");

                    b.HasKey("ID");

                    b.ToTable("TemporaryNewPatients");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.UKOutwardCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("ID");

                    b.ToTable("UKOutwardCodes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.UKPostCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("ID");

                    b.ToTable("UKPostCodes");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("UnitOfMeasurements");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.ImmunologyExamination", b =>
                {
                    b.HasBaseType("AspergillosisEPR.Models.Patients.PatientExamination");


                    b.ToTable("ImmunologyExamination");

                    b.HasDiscriminator().HasValue("ImmunologyExamination");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MeasurementExamination", b =>
                {
                    b.HasBaseType("AspergillosisEPR.Models.Patients.PatientExamination");


                    b.ToTable("MeasurementExamination");

                    b.HasDiscriminator().HasValue("MeasurementExamination");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.RadiologyExamination", b =>
                {
                    b.HasBaseType("AspergillosisEPR.Models.Patients.PatientExamination");


                    b.ToTable("RadiologyExamination");

                    b.HasDiscriminator().HasValue("RadiologyExamination");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.SGRQExamination", b =>
                {
                    b.HasBaseType("AspergillosisEPR.Models.Patients.PatientExamination");


                    b.ToTable("SGRQExamination");

                    b.HasDiscriminator().HasValue("SGRQExamination");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportForm", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormCategory", "CaseReportFormCategory")
                        .WithMany()
                        .HasForeignKey("CaseReportFormCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormField", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFieldType", "CaseReportFormFieldType")
                        .WithMany()
                        .HasForeignKey("CaseReportFormFieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportForm", "CaseReportForm")
                        .WithMany("Fields")
                        .HasForeignKey("CaseReportFormId");

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormSection", "CaseReportFormSection")
                        .WithMany("CaseReportFormResultFields")
                        .HasForeignKey("CaseReportFormSectionId");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFieldOption", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormField", "Field")
                        .WithMany("Options")
                        .HasForeignKey("CaseReportFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormOptionChoice", "Option")
                        .WithMany()
                        .HasForeignKey("CaseReportFormOptionChoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormFormSection", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportForm")
                        .WithMany("Sections")
                        .HasForeignKey("CaseReportFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormSection", "Section")
                        .WithMany("FormSections")
                        .HasForeignKey("CaseReportFormSectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormOptionChoice", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormOptionGroup", "CaseReportFormOptionGroup")
                        .WithMany("Choices")
                        .HasForeignKey("CaseReportFormOptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormPatientResult", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormField", "Field")
                        .WithMany()
                        .HasForeignKey("CaseReportFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportForm", "FormResult")
                        .WithMany()
                        .HasForeignKey("CaseReportFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormResult")
                        .WithMany("Results")
                        .HasForeignKey("CaseReportFormResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormPatientResultOptionChoice", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormPatientResult")
                        .WithMany("Options")
                        .HasForeignKey("CaseReportFormPatientResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.CaseReportForms.CaseReportFormResult", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportFormCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CaseReportFormCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.CaseReportForms.CaseReportForm", "Form")
                        .WithMany()
                        .HasForeignKey("CaseReportFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("CaseReportFormResults")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrial", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.MedicalTrials.MedicalTrialPrincipalInvestigator", "PrincipalInvestigator")
                        .WithMany()
                        .HasForeignKey("MedicalTrialPrincipalInvestigatorId");

                    b.HasOne("AspergillosisEPR.Models.MedicalTrials.MedicalTrialStatus", "TrialStatus")
                        .WithMany()
                        .HasForeignKey("MedicalTrialStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.MedicalTrials.MedicalTrialType", "TrialType")
                        .WithMany()
                        .HasForeignKey("MedicalTrialTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.MedicalTrials.MedicalTrialPrincipalInvestigator", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.PersonTitle", "PersonTitle")
                        .WithMany()
                        .HasForeignKey("PersonTitleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patient", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patients.PatientStatus", "PatientStatus")
                        .WithMany()
                        .HasForeignKey("PatientStatusId");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientAllergicIntoleranceItem", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("PatientAllergicIntoleranceItems")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientAllergicIntoleranceItemSideEffect", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patients.PatientAllergicIntoleranceItem", "PatientAllergicIntoleranceItem")
                        .WithMany("SideEffects")
                        .HasForeignKey("PatientAllergicIntoleranceItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.SideEffect", "SideEffect")
                        .WithMany()
                        .HasForeignKey("SideEffectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDiagnosis", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.DiagnosisCategory", "DiagnosisCategory")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("DiagnosisCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.DiagnosisType", "DiagnosisType")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("DiagnosisTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrug", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("PatientDrugs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrugLevel", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("DrugLevels")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientDrugSideEffect", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patients.PatientDrug", "PatientDrug")
                        .WithMany("SideEffects")
                        .HasForeignKey("PatientDrugId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.SideEffect", "SideEffect")
                        .WithMany()
                        .HasForeignKey("SideEffectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientExamination", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patients.PatientImmunoglobulin", "PatientImmunoglobulin")
                        .WithMany()
                        .HasForeignKey("PatientImmunoglobulinId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patients.PatientMeasurement", "PatientMeasurement")
                        .WithMany()
                        .HasForeignKey("PatientMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patients.PatientRadiologyFinding", "PatientRadiologyFiniding")
                        .WithMany()
                        .HasForeignKey("PatientRadiologyFinidingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patients.PatientSTGQuestionnaire", "PatientSTGQuestionnaire")
                        .WithMany()
                        .HasForeignKey("PatientSTGQuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patients.PatientVisit", "PatientVisit")
                        .WithMany()
                        .HasForeignKey("PatientVisitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientHaematology", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientHaematologies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientImmunoglobulin", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.ImmunoglobulinType", "ImmunoglobulinType")
                        .WithMany()
                        .HasForeignKey("ImmunoglobulinTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientImmunoglobulines")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientMeasurement", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientMeasurements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientMedicalTrial", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.MedicalTrials.MedicalTrial", "MedicalTrial")
                        .WithMany()
                        .HasForeignKey("MedicalTrialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany("MedicalTrials")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.MedicalTrials.MedicalTrialPatientStatus", "PatientMedicalTrialStatus")
                        .WithMany()
                        .HasForeignKey("PatientMedicalTrialStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientPulmonaryFunctionTest", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientPulmonaryFunctionTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.PulmonaryFunctionTest", "PulmonaryFunctionTest")
                        .WithMany()
                        .HasForeignKey("PulmonaryFunctionTestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientRadiologyFinding", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Radiology.ChestDistribution", "ChestDistribution")
                        .WithMany()
                        .HasForeignKey("ChestDistributionId");

                    b.HasOne("AspergillosisEPR.Models.Radiology.ChestLocation", "ChestLocation")
                        .WithMany()
                        .HasForeignKey("ChestLocationId");

                    b.HasOne("AspergillosisEPR.Models.Radiology.Finding", "Finding")
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Radiology.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientRadiologyFindings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Radiology.RadiologyType", "RadiologyType")
                        .WithMany()
                        .HasForeignKey("RadiologyTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Radiology.TreatmentResponse", "TreatmentResponse")
                        .WithMany()
                        .HasForeignKey("TreatmentResponseId");
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSmokingDrinkingStatus", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithOne("PatientSmokingDrinkingStatus")
                        .HasForeignKey("AspergillosisEPR.Models.Patients.PatientSmokingDrinkingStatus", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.SmokingStatus", "SmokingStatus")
                        .WithMany()
                        .HasForeignKey("SmokingStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSTGQuestionnaire", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("STGQuestionnaires")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientSurgery", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient")
                        .WithMany("PatientSurgeries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Surgery", "Surgery")
                        .WithMany()
                        .HasForeignKey("SurgeryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Patients.PatientVisit", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Reporting.PatientReportItem", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspergillosisEPR.Models.Reporting.Report", "Report")
                        .WithMany("PatientReportItems")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspergillosisEPR.Models.Reporting.Report", b =>
                {
                    b.HasOne("AspergillosisEPR.Models.Reporting.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
